import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { BackgroundBeamsDemo } from "@/components/Background";
import { Navbar, NextUIProvider } from "@nextui-org/react";
import NavbarComp from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vinit Prajapati",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <BackgroundBeamsDemo>
        <NextUIProvider>
            <div className="relative z-20">
              {children} 
            </div>
        </NextUIProvider>
          </BackgroundBeamsDemo>
      </body>
    </html>
  );
}
